// backend/src/services/curatedAttractions.js
// ─────────────────────────────────────────────────────────────────────────────
// Verified Curated Tourist Attraction Dataset
//
// High-quality, verified real-world tourist attractions with precise coordinates,
// categories, typical visit durations, estimated entry costs, and English descriptions.
// Used as an authoritative seed and fallback for itinerary generation.
// ─────────────────────────────────────────────────────────────────────────────

const CURATED_ATTRACTIONS = {
  // ── Vizianagaram (VZM / Andhra Pradesh) ───────────────────────────────────
  vizianagaram: [
    {
      name: 'Ramanarayanam Temple',
      category: 'Culture',
      location: 'Korukonda Road, Vizianagaram',
      address: 'Korukonda Road, Vizianagaram, Andhra Pradesh',
      description: 'Stunning bow-and-arrow shaped spiritual theme complex and temple dedicated to Lord Rama, featuring Valmiki Ramayana sculptures and night illumination.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 18.1472,
      longitude: 83.3985,
    },
    {
      name: 'Sri Pydithalli Ammavari Temple',
      category: 'Culture',
      location: 'Near Railway Station Road, Vizianagaram',
      address: 'Station Road, Vizianagaram, Andhra Pradesh',
      description: 'Historic 300-year-old temple of Goddess Sri Pydithalli Ammavaru, the revered presiding guardian deity of Vizianagaram.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 18.1147,
      longitude: 83.4072,
    },
    {
      name: 'Vizianagaram Fort',
      category: 'Culture',
      location: 'Fort Area, Vizianagaram Centre',
      address: 'Fort Road, Vizianagaram, Andhra Pradesh',
      description: 'Historic 18th-century stone fortress built by Maharaja Vijayarama Gajapati Raju, featuring the grand Moti Mahal and royal court halls.',
      duration: '2 hours',
      estimatedCost: 30,
      latitude: 18.1189,
      longitude: 83.4153,
    },
    {
      name: 'Gantasthambam (Clock Tower)',
      category: 'Culture',
      location: 'Main Town Centre, Vizianagaram',
      address: 'MG Road, Vizianagaram, Andhra Pradesh',
      description: 'Iconic 19th-century British-era stone clock tower standing 68 feet tall, symbolizing the historical heart of the city.',
      duration: '1 hour',
      estimatedCost: 0,
      latitude: 18.1132,
      longitude: 83.4116,
    },
    {
      name: 'Kumili Temple Complex',
      category: 'Culture',
      location: 'Kumili Village, Vizianagaram District',
      address: 'Kumili, Vizianagaram, Andhra Pradesh',
      description: 'Renowned temple complex with intricate stone carvings and idols of Lord Shiva, Ganesha, and Sita Rama inside a fortress-like campus.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 18.0610,
      longitude: 83.4975,
    },
    {
      name: 'Phool Bagh Palace',
      category: 'Culture',
      location: 'Cantonment Area, Vizianagaram',
      address: 'Phool Bagh, Vizianagaram, Andhra Pradesh',
      description: 'Royal garden palace of the Vizianagaram Gajapati dynasty surrounded by sprawling heritage landscapes and historical architecture.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 18.1250,
      longitude: 83.4020,
    },
    {
      name: 'Thatipudi Reservoir & Nature Retreat',
      category: 'Nature',
      location: 'Gantyada Mandal, Vizianagaram District',
      address: 'Thatipudi, Vizianagaram, Andhra Pradesh',
      description: 'Scenic reservoir on the Gosthani River surrounded by dense green hills, offering boat rides, birdwatching, and sunset viewpoints.',
      duration: '3 hours',
      estimatedCost: 150,
      latitude: 18.1678,
      longitude: 83.2045,
    },
    {
      name: 'Bobbili Fort & Royal Heritage',
      category: 'Culture',
      location: 'Bobbili, Vizianagaram District',
      address: 'Bobbili, Vizianagaram District, Andhra Pradesh',
      description: 'Legendary historical war fortress site known for the 1757 Battle of Bobbili, featuring royal armoury collections and heritage architecture.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 18.5726,
      longitude: 83.3644,
    },
    {
      name: 'Jonnada Sivalayam',
      category: 'Culture',
      location: 'Jonnada, Vizianagaram',
      address: 'Jonnada Riverbank, Vizianagaram, Andhra Pradesh',
      description: 'Ancient peaceful riverside Shiva temple known for its spiritual atmosphere and picturesque views along the water.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 18.0489,
      longitude: 83.4612,
    },
    {
      name: 'Punagiri Waterfall & Hilltop Shrine',
      category: 'Nature',
      location: 'Punagiri, S.Kota, Vizianagaram District',
      address: 'Punagiri Hills, Vizianagaram, Andhra Pradesh',
      description: 'Lush mountain waterfall and ancient hill temple tucked inside the Eastern Ghats near Srungavarapukota.',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 18.1165,
      longitude: 83.1580,
    },
  ],

  // ── Visakhapatnam (Vizag) ──────────────────────────────────────────────────
  visakhapatnam: [
    {
      name: 'Kailasagiri Hilltop Park',
      category: 'Nature',
      location: 'Kailasagiri, Visakhapatnam',
      address: 'Hill Top Road, Visakhapatnam, Andhra Pradesh',
      description: 'Expansive hilltop park offering ropeway cable car rides, panoramic views of the Bay of Bengal coastline, and giant Shiva-Parvati statues.',
      duration: '2.5 hours',
      estimatedCost: 150,
      latitude: 17.7490,
      longitude: 83.3425,
    },
    {
      name: 'INS Kursura Submarine Museum',
      category: 'Culture',
      location: 'RK Beach Road, Visakhapatnam',
      address: 'Beach Road, Kirlampudi Layout, Visakhapatnam, Andhra Pradesh',
      description: 'Decommissioned Soviet-built submarine turned into a premier naval museum on the sands of Ramakrishna Beach.',
      duration: '1.5 hours',
      estimatedCost: 100,
      latitude: 17.7140,
      longitude: 83.3215,
    },
    {
      name: 'TU 142 Aircraft Museum',
      category: 'Culture',
      location: 'Opposite Submarine Museum, RK Beach',
      address: 'Beach Road, Visakhapatnam, Andhra Pradesh',
      description: 'Long-range maritime reconnaissance anti-submarine aircraft museum showcasing naval aeronautical history and flight cockpits.',
      duration: '1 hour',
      estimatedCost: 80,
      latitude: 17.7148,
      longitude: 83.3222,
    },
    {
      name: 'Ramakrishna (RK) Beach & Promenade',
      category: 'Nature',
      location: 'Beach Road, Visakhapatnam',
      address: 'RK Beach, Visakhapatnam, Andhra Pradesh',
      description: 'Famous urban coastline promenade perfect for breezy evening strolls, seaside snacks, and visiting the War Memorial.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 17.7205,
      longitude: 83.3271,
    },
    {
      name: 'Simhachalam Temple (Varaha Lakshmi Narasimha)',
      category: 'Culture',
      location: 'Simhachalam Hill, Visakhapatnam',
      address: 'Simhachalam, Visakhapatnam, Andhra Pradesh',
      description: 'Ancient 11th-century medieval hilltop temple dedicated to Lord Narasimha, celebrated for its ornate Kalinga architectural stone carvings.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 17.7600,
      longitude: 83.2285,
    },
    {
      name: 'Yarada Beach & Dolphin\'s Nose Lighthouse',
      category: 'Nature',
      location: 'Yarada, Visakhapatnam',
      address: 'Yarada Coast, Visakhapatnam, Andhra Pradesh',
      description: 'Secluded golden-sand beach sheltered by lush hill slopes and the iconic Dolphin\'s Nose rocky headland and lighthouse.',
      duration: '3 hours',
      estimatedCost: 50,
      latitude: 17.6508,
      longitude: 83.2670,
    },
    {
      name: 'Rushikonda Beach & Watersports',
      category: 'Adventure',
      location: 'Rushikonda, Visakhapatnam',
      address: 'Rushikonda, Visakhapatnam, Andhra Pradesh',
      description: 'Blue Flag-certified pristine beach with emerald waters, ideal for swimming, surfing, jet skiing, and coastal photography.',
      duration: '2.5 hours',
      estimatedCost: 350,
      latitude: 17.7818,
      longitude: 83.3855,
    },
    {
      name: 'Borra Caves (Ananthagiri Hills)',
      category: 'Adventure',
      location: 'Ananthagiri Hills, near Vizag',
      address: 'Borra Caves, Alluri Sitharama Raju District, Andhra Pradesh',
      description: 'Deepest limestone karst cave formations in India with million-year-old stalactites and stalagmites illuminated in colorful lighting.',
      duration: '3 hours',
      estimatedCost: 150,
      latitude: 18.2800,
      longitude: 83.0400,
    },
    {
      name: 'Araku Valley Coffee Plantations & Tribal Museum',
      category: 'Nature',
      location: 'Araku Valley',
      address: 'Araku, Andhra Pradesh',
      description: 'Enchanting hill valley featuring organic coffee plantations, Padmapuram botanical gardens, and an authentic tribal heritage museum.',
      duration: '3.5 hours',
      estimatedCost: 100,
      latitude: 18.3266,
      longitude: 82.8741,
    },
    {
      name: 'Thotlakonda Buddhist Complex',
      category: 'Culture',
      location: 'Bheemunipatnam Road, Visakhapatnam',
      address: 'Thotlakonda Hill, Visakhapatnam, Andhra Pradesh',
      description: '2,000-year-old hilltop Buddhist monastic ruins overlooking the sea with stupas, chaityas, and meditative rock-cut water cisterns.',
      duration: '1.5 hours',
      estimatedCost: 20,
      latitude: 17.8256,
      longitude: 83.4147,
    },
  ],

  // ── Amritsar ───────────────────────────────────────────────────────────────
  amritsar: [
    {
      name: 'Golden Temple (Harmandir Sahib)',
      category: 'Culture',
      location: 'Amritsar Central',
      address: 'Golden Temple Road, Amritsar, Punjab',
      description: 'Spiritual heart of Sikhism covered in 500kg of pure gold foil, surrounded by the sacred Amrit Sarovar and housing the world\'s largest community kitchen (Langar).',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 31.6200,
      longitude: 74.8765,
    },
    {
      name: 'Jallianwala Bagh Memorial',
      category: 'Culture',
      location: 'Near Golden Temple',
      address: 'Golden Temple Road, Amritsar, Punjab',
      description: 'Historic public garden and sacred national memorial commemorating the fateful 1919 gathering, preserving bullet marks and the Martyrs\' Well.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 31.6206,
      longitude: 74.8801,
    },
    {
      name: 'Wagah Border Beating Retreat Ceremony',
      category: 'Culture',
      location: 'Attari-Wagah Border',
      address: 'Wagah Border, Amritsar, Punjab',
      description: 'Electrifying military drill and lowering-of-the-flags ceremony performed daily by Indian BSF and Pakistan Rangers at sunset.',
      duration: '3.5 hours',
      estimatedCost: 0,
      latitude: 31.6046,
      longitude: 74.5724,
    },
    {
      name: 'Partition Museum',
      category: 'Culture',
      location: 'Town Hall, Amritsar',
      address: 'Town Hall, Amritsar, Punjab',
      description: 'The world\'s first museum dedicated to the 1947 Partition of British India, housing oral histories, refugee artifacts, and emotional exhibits.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 31.6247,
      longitude: 74.8778,
    },
    {
      name: 'Gobindgarh Fort & Heritage Complex',
      category: 'Culture',
      location: 'Old Cantt Road, Amritsar',
      address: 'Vijay Chowk, Amritsar, Punjab',
      description: '18th-century fortress of Maharaja Ranjit Singh featuring the Toshakhana coin museum, 7D shows, and live martial arts demonstrations.',
      duration: '2.5 hours',
      estimatedCost: 150,
      latitude: 31.6288,
      longitude: 74.8569,
    },
    {
      name: 'Durgiana Temple (Lakshmi Narayan Temple)',
      category: 'Culture',
      location: 'Near Hathi Gate, Amritsar',
      address: 'Durgiana Temple, Amritsar, Punjab',
      description: 'Historic 16th-century Hindu temple dedicated to Goddess Durga, built in architectural style reminiscent of the Golden Temple inside a holy sarovar.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 31.6315,
      longitude: 74.8690,
    },
  ],

  // ── Mumbai ─────────────────────────────────────────────────────────────────
  mumbai: [
    {
      name: 'Gateway of India & Mumbai Harbour',
      category: 'Culture',
      location: 'Apollo Bunder, Colaba, South Mumbai',
      address: 'Apollo Bandar, Colaba, Mumbai, Maharashtra',
      description: 'Grand 26-meter basalt triumphal arch monument built in Indo-Saracenic style overlooking the Arabian Sea, standing opposite the Taj Mahal Palace.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 18.9220,
      longitude: 72.8347,
    },
    {
      name: 'Marine Drive & Girgaon Chowpatty',
      category: 'Nature',
      location: 'Netaji Subhash Chandra Bose Road',
      address: 'Marine Drive, Mumbai, Maharashtra',
      description: 'Famous 3.6-kilometer C-shaped coastal boulevard known as the Queen\'s Necklace, famous for breezy promenades and sunset street snacks.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 18.9432,
      longitude: 72.8230,
    },
    {
      name: 'Elephanta Caves (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Elephanta Island, Mumbai Harbour',
      address: 'Gharapuri, Mumbai Harbour, Maharashtra',
      description: 'Ancient 5th to 8th century rock-cut cave temples dedicated to Lord Shiva, featuring the monumental three-headed Trimurti sculpture.',
      duration: '4 hours',
      estimatedCost: 350,
      latitude: 18.9633,
      longitude: 72.9315,
    },
    {
      name: 'Chhatrapati Shivaji Maharaj Vastu Sangrahalaya (CSMVS Museum)',
      category: 'Culture',
      location: 'Fort, South Mumbai',
      address: '159-161 MG Road, Fort, Mumbai, Maharashtra',
      description: 'Premier heritage art and history museum housed in a majestic Grade-I heritage building, containing over 50,000 ancient artifacts.',
      duration: '2.5 hours',
      estimatedCost: 150,
      latitude: 18.9269,
      longitude: 72.8327,
    },
    {
      name: 'Bandra Bandstand & Castella de Aguada',
      category: 'Nature',
      location: 'Bandra West, Mumbai',
      address: 'Bandstand Promenade, Bandra West, Mumbai, Maharashtra',
      description: 'Scenic cliffside coastal promenade overlooking the sea and Bandra-Worli Sea Link, featuring the 17th-century Portuguese coastal fort.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 19.0416,
      longitude: 72.8184,
    },
    {
      name: 'Sanjay Gandhi National Park & Kanheri Caves',
      category: 'Adventure',
      location: 'Borivali East, Mumbai',
      address: 'Western Express Highway, Borivali East, Mumbai, Maharashtra',
      description: 'Vast urban wildlife reserve with dense forest trails, wildlife safaris, and over 100 basalt rock-cut Buddhist caves dating from the 1st century BC.',
      duration: '3.5 hours',
      estimatedCost: 200,
      latitude: 19.2288,
      longitude: 72.9182,
    },
    {
      name: 'Haji Ali Dargah & Promenade',
      category: 'Culture',
      location: 'Worli Coast, Mumbai',
      address: 'Dargah Road, Haji Ali, Mumbai, Maharashtra',
      description: 'Famous 15th-century Indo-Islamic shrine and mosque perched on an islet in the Arabian Sea, accessible via a narrow causeway during low tide.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 18.9772,
      longitude: 72.8105,
    },
  ],

  // ── Jaipur ─────────────────────────────────────────────────────────────────
  jaipur: [
    {
      name: 'Amber Fort (Amer Palace)',
      category: 'Culture',
      location: 'Amer, Jaipur',
      address: 'Devisinghpura, Amer, Jaipur, Rajasthan',
      description: 'Opulent hilltop fortress built of red sandstone and marble, famous for the glittering Sheesh Mahal (Mirror Palace) and Maota Lake reflections.',
      duration: '3 hours',
      estimatedCost: 100,
      latitude: 26.9855,
      longitude: 75.8513,
    },
    {
      name: 'Hawa Mahal (Palace of Winds)',
      category: 'Culture',
      location: 'Badi Choupad, Old City, Jaipur',
      address: 'Hawa Mahal Road, Badi Choupad, Jaipur, Rajasthan',
      description: 'Iconic 5-story pink sandstone honeycomb facade with 953 jharokhas (windows) designed for royal Rajput women to observe street life unseen.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 26.9239,
      longitude: 75.8267,
    },
    {
      name: 'City Palace Jaipur',
      category: 'Culture',
      location: 'Old City, Jaipur',
      address: 'Tulsi Marg, Gangori Bazaar, J.D.A. Market, Jaipur, Rajasthan',
      description: 'Regal palace complex blending Rajput, Mughal, and European architecture, containing royal costume galleries, courtyards, and Peacock Gate.',
      duration: '2.5 hours',
      estimatedCost: 300,
      latitude: 26.9258,
      longitude: 75.8237,
    },
    {
      name: 'Jantar Mantar (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Gangori Bazaar, Jaipur',
      address: 'Jantar Mantar, Gangori Bazaar, Jaipur, Rajasthan',
      description: 'World\'s largest stone astronomical observatory built by Maharaja Sawai Jai Singh II in 1734, featuring 19 architectural instruments.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 26.9248,
      longitude: 75.8246,
    },
    {
      name: 'Nahargarh Fort & Sunset Panorama',
      category: 'Adventure',
      location: 'Aravalli Hills, Jaipur',
      address: 'Krishna Nagar, Brahampuri, Jaipur, Rajasthan',
      description: 'Hilltop fort perched on the edge of the Aravalli hills offering sweeping panoramic views and the best sunset vista over the Pink City.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 26.9370,
      longitude: 75.8156,
    },
    {
      name: 'Jal Mahal (Water Palace)',
      category: 'Nature',
      location: 'Man Sagar Lake, Jaipur',
      address: 'Amer Road, Jal Mahal, Jaipur, Rajasthan',
      description: 'Stunning 18th-century Rajput palace submerged in the calm waters of Man Sagar Lake, surrounded by picturesque Aravalli mountains.',
      duration: '1 hour',
      estimatedCost: 0,
      latitude: 26.9535,
      longitude: 75.8462,
    },
    {
      name: 'Albert Hall Museum (Central Museum)',
      category: 'Culture',
      location: 'Ram Niwas Garden, Jaipur',
      address: 'Museum Road, Ram Niwas Garden, Jaipur, Rajasthan',
      description: 'Oldest museum of Rajasthan built in grand Indo-Saracenic style, showcasing miniature paintings, Persian carpets, and Egyptian mummies.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 26.9116,
      longitude: 75.8195,
    },
  ],

  // ── Delhi ──────────────────────────────────────────────────────────────────
  delhi: [
    {
      name: 'Qutub Minar Complex (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Mehrauli, South Delhi',
      address: 'Seth Sarai, Mehrauli, New Delhi, Delhi',
      description: '73-meter tall red sandstone victory minaret dating back to 1192, surrounded by the 4th-century rust-resistant Iron Pillar of Delhi.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 28.5245,
      longitude: 77.1855,
    },
    {
      name: 'Humayun\'s Tomb (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Nizamuddin East, New Delhi',
      address: 'Mathura Road, Nizamuddin East, New Delhi, Delhi',
      description: 'Grand 16th-century Mughal garden tomb in red sandstone that directly inspired the architectural design of the Taj Mahal.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 28.5933,
      longitude: 77.2507,
    },
    {
      name: 'Red Fort (Lal Qila)',
      category: 'Culture',
      location: 'Old Delhi',
      address: 'Netaji Subhash Marg, Lal Qila, Chandni Chowk, Delhi',
      description: 'Historic 17th-century Mughal imperial palace fortress in red sandstone, housing the Diwan-i-Aam, Diwan-i-Khas, and royal pavilions.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 28.6562,
      longitude: 77.2410,
    },
    {
      name: 'India Gate & Kartavya Path',
      category: 'Culture',
      location: 'Central Delhi',
      address: 'Kartavya Path, India Gate, New Delhi, Delhi',
      description: '42-meter high triumphal arch war memorial dedicated to Indian soldiers, surrounded by lush lawns, fountains, and the National War Memorial.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 28.6129,
      longitude: 77.2295,
    },
    {
      name: 'Lodhi Gardens',
      category: 'Nature',
      location: 'Lodhi Estate, New Delhi',
      address: 'Lodhi Road, New Delhi, Delhi',
      description: 'Sprawling 90-acre heritage city park dotted with 15th-century Sayyid and Lodi dynastic tombs, lush trees, and tranquil walking trails.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 28.5931,
      longitude: 77.2197,
    },
    {
      name: 'Swaminarayan Akshardham Temple',
      category: 'Culture',
      location: 'NH 24, East Delhi',
      address: 'Noida Mor, Pandav Nagar, New Delhi, Delhi',
      description: 'Vast spiritual Hindu temple campus carved entirely from Rajasthani pink sandstone and Italian Carrara marble, featuring musical fountains.',
      duration: '3.5 hours',
      estimatedCost: 0,
      latitude: 28.6127,
      longitude: 77.2773,
    },
  ],

  // ── Goa ────────────────────────────────────────────────────────────────────
  goa: [
    {
      name: 'Basilica of Bom Jesus (Old Goa)',
      category: 'Culture',
      location: 'Old Goa',
      address: 'Old Goa Road, Bainguinim, Goa',
      description: 'UNESCO World Heritage 16th-century baroque Catholic basilica holding the sacred mortal remains of St. Francis Xavier.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 15.5009,
      longitude: 73.9116,
    },
    {
      name: 'Fort Aguada & Lighthouse',
      category: 'Culture',
      location: 'Sinquerim, North Goa',
      address: 'Aguada-Siolim Road, Sinquerim, Candolim, Goa',
      description: 'Well-preserved 17th-century Portuguese fortress and vintage lighthouse overlooking the confluence of the Mandovi River and Arabian Sea.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 15.4920,
      longitude: 73.7736,
    },
    {
      name: 'Dudhsagar Waterfalls',
      category: 'Adventure',
      location: 'Mollem National Park, South Goa',
      address: 'Sonaulim, Goa',
      description: 'Spectacular 310-meter four-tiered milky waterfall in the Western Ghats jungle, famous for jeep safaris and scenic railway bridges.',
      duration: '4 hours',
      estimatedCost: 500,
      latitude: 15.3144,
      longitude: 74.3144,
    },
    {
      name: 'Palolem Beach',
      category: 'Nature',
      location: 'Canacona, South Goa',
      address: 'Palolem, Canacona, Goa',
      description: 'Crescent-shaped paradise beach with calm shallow waters, colourful beach shacks, and dolphin-spotting boat trips.',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 15.0109,
      longitude: 74.0283,
    },
    {
      name: 'Chapora Fort & Vagator Coastline',
      category: 'Culture',
      location: 'Chapora, North Goa',
      address: 'Chapora Fort Trail, Vagator, Goa',
      description: 'Historic red-laterite clifftop fortress offering magnificent sunset panoramas over the Chapora River estuary and Vagator Beach.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 15.6058,
      longitude: 73.7364,
    },
    {
      name: 'Fontainhas Latin Quarter Heritage Walk',
      category: 'Culture',
      location: 'Panaji, Goa',
      address: 'Fontainhas, Mala, Panaji, Goa',
      description: 'Charming heritage neighbourhood with vibrant Portuguese colonial houses, narrow cobblestone alleys, and traditional art galleries.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 15.4989,
      longitude: 73.8315,
    },
  ],

  // ── Kerala ─────────────────────────────────────────────────────────────────
  kerala: [
    {
      name: 'Munnar Tea Estates & Mattupetty Dam',
      category: 'Nature',
      location: 'Munnar, Idukki District',
      address: 'Munnar, Kerala',
      description: 'Rolling velvet-green tea gardens in the misty Western Ghats hills, paired with the serene waters and speedboating at Mattupetty Dam.',
      duration: '3 hours',
      estimatedCost: 200,
      latitude: 10.0889,
      longitude: 77.0595,
    },
    {
      name: 'Eravikulam National Park (Rajamalai)',
      category: 'Nature',
      location: 'Munnar Hills, Kerala',
      address: 'Kannar Devan Hills, Munnar, Kerala',
      description: 'High-altitude protected sanctuary home to the endangered Nilgiri Tahr mountain goat and the highest peak in South India, Anamudi.',
      duration: '3 hours',
      estimatedCost: 200,
      latitude: 10.1500,
      longitude: 77.0667,
    },
    {
      name: 'Alleppey Backwaters & Houseboat Cruise',
      category: 'Nature',
      location: 'Alappuzha, Kerala',
      address: 'Punnamada, Alappuzha, Kerala',
      description: 'World-famous labyrinth of tranquil palm-fringed lagoons, emerald canals, and traditional Kettuvallam wooden houseboats.',
      duration: '4 hours',
      estimatedCost: 1000,
      latitude: 9.4981,
      longitude: 76.3388,
    },
    {
      name: 'Fort Kochi Heritage & Chinese Fishing Nets',
      category: 'Culture',
      location: 'Kochi, Kerala',
      address: 'Fort Kochi, Kochi, Kerala',
      description: 'Historic colonial seaside quarter featuring iconic 14th-century cantilevered Chinese fishing nets, St. Francis Church, and spice markets.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 9.9660,
      longitude: 76.2425,
    },
    {
      name: 'Varkala Cliff & Papanasam Beach',
      category: 'Nature',
      location: 'Varkala, Thiruvananthapuram District',
      address: 'Varkala Cliff, Varkala, Kerala',
      description: 'Breathtaking red sedimentary cliffside path overlooking the Arabian Sea, known for sunset viewpoints, cliffside cafes, and natural springs.',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 8.7341,
      longitude: 76.7060,
    },
    {
      name: 'Athirappilly Waterfalls',
      category: 'Nature',
      location: 'Chalakudy, Thrissur District',
      address: 'Athirappilly, Kerala',
      description: 'Majestic 80-foot wide cascading waterfall known as the "Niagara of South India," surrounded by dense Western Ghats rainforests.',
      duration: '3 hours',
      estimatedCost: 100,
      latitude: 10.2851,
      longitude: 76.5698,
    },
  ],

  // ── Ladakh / Leh ───────────────────────────────────────────────────────────
  ladakh: [
    {
      name: 'Pangong Tso Lake',
      category: 'Nature',
      location: 'Changtang Plateau, Ladakh',
      address: 'Pangong Tso, Ladakh',
      description: 'World\'s highest saltwater lake at 4,350 meters altitude, spanning 134km with surreal color-shifting waters from deep blue to turquoise.',
      duration: '4 hours',
      estimatedCost: 200,
      latitude: 33.7595,
      longitude: 78.6674,
    },
    {
      name: 'Nubra Valley & Hunder Sand Dunes',
      category: 'Adventure',
      location: 'Nubra Valley, Ladakh',
      address: 'Hunder, Nubra Valley, Ladakh',
      description: 'High-altitude cold desert valley famous for Bactrian double-humped camel safaris amidst rolling white sand dunes and snowy peaks.',
      duration: '4 hours',
      estimatedCost: 350,
      latitude: 34.5833,
      longitude: 77.4667,
    },
    {
      name: 'Leh Palace & Tsemo Fort',
      category: 'Culture',
      location: 'Leh Town, Ladakh',
      address: 'Namgyal Hill, Leh, Ladakh',
      description: 'Historic 17th-century 9-story royal Tibetan palace built by King Sengge Namgyal, offering panoramic vistas over Leh and the Stok Kangri range.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 34.1642,
      longitude: 77.5848,
    },
    {
      name: 'Shanti Stupa',
      category: 'Culture',
      location: 'Changsps, Leh, Ladakh',
      address: 'Shanti Stupa Road, Leh, Ladakh',
      description: 'Magnificent white-domed Buddhist stupa atop a steep hill, offering 360-degree sunset and sunrise vistas over the Leh valley.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 34.1706,
      longitude: 77.5756,
    },
    {
      name: 'Thiksey Monastery',
      category: 'Culture',
      location: 'Thiksey, Leh District',
      address: 'Thiksey, Ladakh',
      description: 'Imposing 12-story hilltop Tibetan Buddhist monastery resembling Lhasa\'s Potala Palace, housing a 15-meter statue of Maitreya Buddha.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 34.0583,
      longitude: 77.6667,
    },
    {
      name: 'Magnetic Hill & Indus-Zanskar Sangam',
      category: 'Adventure',
      location: 'Leh-Srinagar Highway',
      address: 'Nimmu, Ladakh',
      description: 'Mysterious gravity-defying optical illusion road section paired with the dramatic confluence of the mud-colored Indus and emerald Zanskar rivers.',
      duration: '2.5 hours',
      estimatedCost: 0,
      latitude: 34.1950,
      longitude: 77.3500,
    },
  ],

  // ── Manali ─────────────────────────────────────────────────────────────────
  manali: [
    {
      name: 'Solang Valley Adventure Arena',
      category: 'Adventure',
      location: 'Solang, Manali',
      address: 'Solang Valley, Manali, Himachal Pradesh',
      description: 'Premier mountain adventure destination offering paragliding, zorbing, quad biking, and scenic cable car ropeway rides amidst snow peaks.',
      duration: '3.5 hours',
      estimatedCost: 800,
      latitude: 32.3167,
      longitude: 77.1500,
    },
    {
      name: 'Rohtang Pass Snow Viewpoint',
      category: 'Adventure',
      location: 'Pir Panjal Range, Manali',
      address: 'Rohtang Pass, Himachal Pradesh',
      description: 'High Himalayan mountain pass at 3,978 meters connecting Kullu Valley with Lahaul and Spiti, offering breathtaking glacier and snow views.',
      duration: '4 hours',
      estimatedCost: 500,
      latitude: 32.3716,
      longitude: 77.2466,
    },
    {
      name: 'Hidimba Devi Temple',
      category: 'Culture',
      location: 'Dhungri Forest, Old Manali',
      address: 'Hadimba Temple Road, Old Manali, Himachal Pradesh',
      description: 'Ancient 1553 pagoda-style wooden temple dedicated to Goddess Hidimba, nestled inside an enchanting forest of towering deodar cedars.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 32.2452,
      longitude: 77.1888,
    },
    {
      name: 'Jogini Waterfalls & Vashisht Hot Springs',
      category: 'Nature',
      location: 'Vashisht Village, Manali',
      address: 'Vashisht, Manali, Himachal Pradesh',
      description: 'Scenic pine forest trek leading to the cascading Jogini Falls, paired with a dip in the natural mineral-rich sulfur hot springs of Vashisht.',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 32.2644,
      longitude: 77.1956,
    },
    {
      name: 'Old Manali Village & Cultural Cafes',
      category: 'Culture',
      location: 'Old Manali',
      address: 'Old Manali, Himachal Pradesh',
      description: 'Rustic Himalayan village featuring traditional wooden houses, apple orchards, bohemian music cafes, and local craft shops.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 32.2530,
      longitude: 77.1780,
    },
    {
      name: 'Atal Tunnel & Sissu Valley',
      category: 'Adventure',
      location: 'Lahaul Valley, near Manali',
      address: 'Atal Tunnel North Portal, Sissu, Himachal Pradesh',
      description: 'Journey through the world\'s longest highway tunnel above 10,000 feet into the alpine wonderland and waterfalls of Sissu in Lahaul.',
      duration: '4 hours',
      estimatedCost: 200,
      latitude: 32.4833,
      longitude: 77.1167,
    },
  ],

  // ── Srinagar ───────────────────────────────────────────────────────────────
  srinagar: [
    {
      name: 'Dal Lake & Shikara Cruise',
      category: 'Nature',
      location: 'Boulevard Road, Srinagar',
      address: 'Dal Lake, Srinagar, Jammu & Kashmir',
      description: 'Iconic Jewel in the Crown of Kashmir featuring sunset wooden Shikara gondola rides past floating lotus gardens and traditional houseboats.',
      duration: '3 hours',
      estimatedCost: 500,
      latitude: 34.0837,
      longitude: 74.8370,
    },
    {
      name: 'Shalimar Bagh Mughal Garden',
      category: 'Culture',
      location: 'Dal Lake North, Srinagar',
      address: 'Shalimar, Srinagar, Jammu & Kashmir',
      description: 'Imperial 1619 Mughal terraced garden built by Emperor Jahangir for Empress Nur Jahan, with cascading fountains, chinar trees, and royal pavilions.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 34.1492,
      longitude: 74.8722,
    },
    {
      name: 'Nishat Bagh (Garden of Bliss)',
      category: 'Culture',
      location: 'Boulevard Road, Srinagar',
      address: 'Nishat, Srinagar, Jammu & Kashmir',
      description: '12-terraced garden rising steeply from the shores of Dal Lake against the dramatic backdrop of the Zabarwan mountain range.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 34.1250,
      longitude: 74.8780,
    },
    {
      name: 'Shankaracharya Temple',
      category: 'Culture',
      location: 'Gopadri Hill, Srinagar',
      address: 'Durgjan, Srinagar, Jammu & Kashmir',
      description: 'Ancient 9th-century stone temple dedicated to Lord Shiva situated 1,000 feet above the valley floor, offering spectacular panoramas over Srinagar.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 34.0769,
      longitude: 74.8344,
    },
    {
      name: 'Pari Mahal (Palace of Fairies)',
      category: 'Culture',
      location: 'Zabarwan Range, Srinagar',
      address: 'Pari Mahal, Srinagar, Jammu & Kashmir',
      description: 'Seven-terraced 17th-century palace built by Prince Dara Shikoh as an astrological school, overlooking the full expanse of Dal Lake.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 34.0878,
      longitude: 74.8697,
    },
    {
      name: 'Indira Gandhi Memorial Tulip Garden',
      category: 'Nature',
      location: 'Cheshmashahi, Srinagar',
      address: 'Siraj Bagh, Srinagar, Jammu & Kashmir',
      description: 'Largest tulip garden in Asia spanning 30 hectares at the foothills of Zabarwan hills, displaying millions of blooming tulips.',
      duration: '2 hours',
      estimatedCost: 100,
      latitude: 34.0950,
      longitude: 74.8730,
    },
  ],

  // ── Agra ───────────────────────────────────────────────────────────────────
  agra: [
    {
      name: 'Taj Mahal (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Dharmapuri, Forest Colony, Agra',
      address: 'Taj Mahal, Dharmapuri, Agra, Uttar Pradesh',
      description: 'World-famous 17th-century white marble mausoleum built by Emperor Shah Jahan for Mumtaz Mahal, one of the Seven Wonders of the World.',
      duration: '3 hours',
      estimatedCost: 50,
      latitude: 27.1751,
      longitude: 78.0421,
    },
    {
      name: 'Agra Fort (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Rakabganj, Agra',
      address: 'Agra Fort, Rakabganj, Agra, Uttar Pradesh',
      description: 'Massive 16th-century red sandstone imperial stronghold and principal royal residence of the Mughal emperors until 1638.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 27.1795,
      longitude: 78.0211,
    },
    {
      name: 'Mehtab Bagh (Moonlight Garden)',
      category: 'Nature',
      location: 'Nagla Devjit, Agra',
      address: 'Opposite Taj Mahal, Yamuna River, Agra, Uttar Pradesh',
      description: 'Charbagh garden complex situated on the opposite bank of the Yamuna River, providing unobstructed sunset views of the Taj Mahal.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 27.1800,
      longitude: 78.0425,
    },
    {
      name: 'Fatehpur Sikri (UNESCO World Heritage)',
      category: 'Culture',
      location: 'Fatehpur Sikri, Agra District',
      address: 'Fatehpur Sikri, Uttar Pradesh',
      description: 'Preserved 16th-century royal capital of Emperor Akbar featuring the towering 54-meter Buland Darwaza and Salim Chishti tomb.',
      duration: '3 hours',
      estimatedCost: 50,
      latitude: 27.0945,
      longitude: 77.6679,
    },
    {
      name: 'Tomb of I\'timad-ud-Daulah (Baby Taj)',
      category: 'Culture',
      location: 'Moti Bagh, Agra',
      address: 'Shantir Nagar, Moti Bagh, Agra, Uttar Pradesh',
      description: 'Exquisite jewel-box marble tomb featuring the earliest extensive use of pietra dura inlay work in Mughal architecture.',
      duration: '1.5 hours',
      estimatedCost: 50,
      latitude: 27.1927,
      longitude: 78.0310,
    },
  ],

  // ── Alappuzha (Alleppey) ───────────────────────────────────────────────────
  alappuzha: [
    {
      name: 'Alleppey Backwaters Canal Cruise',
      category: 'Nature',
      location: 'Punnamada Jetty, Alappuzha',
      address: 'Punnamada, Alappuzha, Kerala',
      description: 'Iconic serene cruise on traditional thatched-roof boats gliding through palm-shaded canals, paddy fields, and tranquil backwater villages.',
      duration: '4 hours',
      estimatedCost: 800,
      latitude: 9.4981,
      longitude: 76.3388,
    },
    {
      name: 'Alappuzha Beach & Historic Pier',
      category: 'Nature',
      location: 'Alappuzha Coast',
      address: 'Beach Road, Alappuzha, Kerala',
      description: 'Scenic sandy coast featuring the remains of a 150-year-old historic marine pier, an active candy-striped lighthouse, and sunset sea views.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 9.4930,
      longitude: 76.3190,
    },
    {
      name: 'Marari Beach & Coastal Village',
      category: 'Nature',
      location: 'Mararikulam, Alappuzha',
      address: 'Marari Beach, Mararikulam, Alappuzha, Kerala',
      description: 'Quiet, untouched coconut-grove beach ideal for relaxing walks, watching traditional fishermen at sea, and beach hammocks.',
      duration: '2.5 hours',
      estimatedCost: 0,
      latitude: 9.6000,
      longitude: 76.2970,
    },
    {
      name: 'Kuttanad Below-Sea-Level Paddy Fields',
      category: 'Nature',
      location: 'Kuttanad Region, Alappuzha',
      address: 'Kuttanad, Alappuzha, Kerala',
      description: 'Known as the "Rice Bowl of Kerala," one of the few places in the world where farming is carried out 4 to 10 feet below sea level.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 9.5655,
      longitude: 76.3913,
    },
    {
      name: 'Krishnapuram Palace & Museum',
      category: 'Culture',
      location: 'Kayamkulam, Alappuzha District',
      address: 'Oachira Road, Kayamkulam, Kerala',
      description: '18th-century Travancore royal palace built in traditional Kerala architectural style, displaying the famous Gajendra Moksham mural painting.',
      duration: '2 hours',
      estimatedCost: 30,
      latitude: 9.1712,
      longitude: 76.5188,
    },
  ],

  // ── Patna (Bihar) ───────────────────────────────────────────────────────────
  patna: [
    {
      name: 'Golghar Granary & Panoramic Viewpoint',
      category: 'Culture',
      location: 'Near Gandhi Maidan, Patna',
      address: 'Ashok Rajpath, Patna, Bihar',
      description: 'Iconic 1786 beehive-shaped massive granary offering spiral stone staircases with sweeping 360-degree views over Patna and the River Ganges.',
      duration: '1.5 hours',
      estimatedCost: 20,
      latitude: 25.6205,
      longitude: 85.1438,
    },
    {
      name: 'Takht Sri Patna Sahib (Gurudwara)',
      category: 'Culture',
      location: 'Old Patna City (Harmandir Gali)',
      address: 'Harmandir Gali, Patna Sahib, Bihar',
      description: 'Revered spiritual birthplace of the tenth Sikh Guru, Guru Gobind Singh Ji, adorned with pristine white marble architecture and sacred relics.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 25.5947,
      longitude: 85.2285,
    },
    {
      name: 'Bihar Museum',
      category: 'Culture',
      location: 'Bailey Road, Patna',
      address: 'Jawaharlal Nehru Marg, Bailey Road, Patna, Bihar',
      description: 'World-class modern museum spanning 13 acres, showcasing ancient Bihari heritage, Mauryan sculptures, and regional tribal folk art.',
      duration: '3 hours',
      estimatedCost: 100,
      latitude: 25.6083,
      longitude: 85.1226,
    },
    {
      name: 'Patna Museum (Jadu Ghar)',
      category: 'Culture',
      location: 'Near Patna Junction, Lodipur',
      address: 'Museum Road, Lodipur, Patna, Bihar',
      description: 'Grand Indo-Saracenic museum housing the world-famous Didarganj Yakshi statue, Buddhist relics, and a 200-million-year-old fossil tree.',
      duration: '2 hours',
      estimatedCost: 50,
      latitude: 25.6094,
      longitude: 85.1378,
    },
    {
      name: 'Buddha Smriti Park (Karuna Stupa)',
      category: 'Relaxation',
      location: 'Frazer Road, near Patna Junction',
      address: 'Frazer Road, Patna, Bihar',
      description: 'Serene 22-acre urban memorial park featuring the 200-foot tall Patliputra Karuna Stupa containing Buddha relics and meditation halls.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 25.6042,
      longitude: 85.1372,
    },
    {
      name: 'Kumhrar (Ancient Pataliputra Excavation Site)',
      category: 'Culture',
      location: 'Kumhrar, East Patna',
      address: 'Kankarbagh Main Road, Kumhrar, Patna, Bihar',
      description: 'Archaeological remains of Emperor Ashoka’s ancient Mauryan imperial capital and the legendary 80-pillar pillared assembly hall.',
      duration: '1.5 hours',
      estimatedCost: 25,
      latitude: 25.5931,
      longitude: 85.1794,
    },
    {
      name: 'Mahavir Mandir (Patna)',
      category: 'Culture',
      location: 'Opposite Patna Junction',
      address: 'Station Road, Patna, Bihar',
      description: 'Ancient and revered Hindu temple dedicated to Lord Hanuman, receiving millions of devotees every year and renowned for its Naivedyam prasadam.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 25.6022,
      longitude: 85.1378,
    },
    {
      name: 'Sabhyata Dwar & Gandhi Ghat Promenade',
      category: 'Nature',
      location: 'Ganga Riverfront, Patna',
      address: 'Ashok Rajpath, NIT Ghat, Patna, Bihar',
      description: 'Majestic 32-meter sandstone triumphal arch celebrating Mauryan civilizational heritage, overlooking the holy Ganges promenade and evening Aarti.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 25.6212,
      longitude: 85.1706,
    },
    {
      name: 'Sanjay Gandhi Biological Park (Patna Zoo)',
      category: 'Nature',
      location: 'Bailey Road, Patna',
      address: 'Raj Bhavan, Bailey Road, Patna, Bihar',
      description: 'Sprawling 150-acre zoological park and botanical garden home to rhinos, tigers, toy train rides, and lush lakeside walking trails.',
      duration: '3 hours',
      estimatedCost: 50,
      latitude: 25.5997,
      longitude: 85.0997,
    },
  ],

  // ── Dimapur (Nagaland) ──────────────────────────────────────────────────────
  dimapur: [
    {
      name: 'Kachari Ruins (Rajbari Medieval Megaliths)',
      category: 'Culture',
      location: 'Walford Area, Dimapur',
      address: 'Rajbari Park, Dimapur, Nagaland',
      description: 'Ancient 10th-century medieval megalithic mushroom-domed carved stone pillars and fortifications belonging to the historic Dimasa Kachari Kingdom.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 25.9085,
      longitude: 93.7315,
    },
    {
      name: 'Nagaland Zoological Park',
      category: 'Nature',
      location: 'Rangapahar, Dimapur',
      address: 'Rangapahar Forest, Dimapur, Nagaland',
      description: 'Lush 176-hectare flora and wildlife sanctuary housing rare Northeast Himalayan species including Hoolock gibbons, hornbills, and leopards.',
      duration: '3 hours',
      estimatedCost: 30,
      latitude: 25.8654,
      longitude: 93.6820,
    },
    {
      name: 'Diezephe Craft & Handloom Village',
      category: 'Culture',
      location: 'Diezephe, Dimapur District',
      address: 'Diezephe Village, Nagaland',
      description: 'Acclaimed heritage crafts center celebrated for traditional Naga wood carvings, bamboo artifacts, and authentic handloom weaving.',
      duration: '2.5 hours',
      estimatedCost: 50,
      latitude: 25.8120,
      longitude: 93.7250,
    },
    {
      name: 'Triple Falls Cascade & Nature Trail',
      category: 'Nature',
      location: 'Seithekima Village, near Dimapur',
      address: 'Seithekima, Chumukedima, Nagaland',
      description: 'Picturesque three-stream waterfall cascading into a natural pool amidst dense rainforests, offering scenic trekking trails.',
      duration: '3.5 hours',
      estimatedCost: 0,
      latitude: 25.7925,
      longitude: 93.8150,
    },
    {
      name: 'Green Park & Horticultural Garden',
      category: 'Relaxation',
      location: '4th Mile, Dimapur',
      address: 'State Horticulture Nursery, 4th Mile, Dimapur, Nagaland',
      description: 'Tranquil state park with botanical gardens, open picnic lawns, children play areas, and pedal boating on a central lake.',
      duration: '2 hours',
      estimatedCost: 20,
      latitude: 25.8750,
      longitude: 93.7550,
    },
    {
      name: 'Nagaland Science Centre & Planetarium',
      category: 'Culture',
      location: 'Behind Super Market, Dimapur',
      address: 'Naga Shopping Arcade, Dimapur, Nagaland',
      description: 'Interactive science museum featuring outdoor science parks, children’s galleries, and an astronomy planetarium show.',
      duration: '2 hours',
      estimatedCost: 25,
      latitude: 25.9050,
      longitude: 93.7380,
    },
    {
      name: 'Chumukedima Ancient Village & Hilltop Viewpoint',
      category: 'Adventure',
      location: 'Chumukedima Hills, Dimapur',
      address: 'Old Chumukedima, Nagaland',
      description: 'Historic British colonial hill post offering panoramic vistas overlooking the entire Dimapur valley and Patkai mountain ranges.',
      duration: '2.5 hours',
      estimatedCost: 0,
      latitude: 25.7820,
      longitude: 93.7850,
    },
  ],

  // ── Bhimavaram (Andhra Pradesh) ───────────────────────────────────────────
  bhimavaram: [
    {
      name: 'Somarama Temple (Sri Someswara Swamy)',
      category: 'Culture',
      location: 'Gunupudi, Bhimavaram',
      address: 'Gunupudi, Bhimavaram, West Godavari, Andhra Pradesh',
      description: 'Ancient 3rd-century Pancharama Kshetra Shiva temple featuring a unique crystal-white Shivalinga that changes color according to lunar phases and the sacred Chandra Pushkarini pond.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 16.5415,
      longitude: 81.5242,
    },
    {
      name: 'Mavullamma Temple (Sri Mavullamma Ammavari Devasthanam)',
      category: 'Culture',
      location: 'Temple Road, Bhimavaram',
      address: 'Mavullamma Temple Street, Bhimavaram, Andhra Pradesh',
      description: 'Revered 13th-century spiritual shrine of Goddess Mavullamma, the beloved gramadevata and presiding protector deity of Bhimavaram.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 16.5438,
      longitude: 81.5230,
    },
    {
      name: 'Ksheera Ramalingeswara Swamy Temple (Palakollu)',
      category: 'Culture',
      location: 'Palakollu, near Bhimavaram',
      address: 'Palakollu, West Godavari District, Andhra Pradesh',
      description: 'Magnificent Pancharama Kshetra temple famed for its 120-foot tall 9-tiered Rajagopuram and ancient milk-white Shivalinga.',
      duration: '2 hours',
      estimatedCost: 0,
      latitude: 16.5295,
      longitude: 81.7285,
    },
    {
      name: 'Perupalem Beach & Bay of Bengal Coastline',
      category: 'Nature',
      location: 'Mogalthur / Perupalem, near Bhimavaram',
      address: 'Perupalem Beach, West Godavari District, Andhra Pradesh',
      description: 'Tranquil golden sand beach on the Bay of Bengal lined with lush casuarina groves and calm coastal waves, ideal for seaside walks and evening sunsets.',
      duration: '3 hours',
      estimatedCost: 0,
      latitude: 16.3685,
      longitude: 81.6095,
    },
    {
      name: 'Dindi & Godavari River Backwaters',
      category: 'Relaxation',
      location: 'Dindi / Razole, near Bhimavaram',
      address: 'Dindi, Konaseema, Andhra Pradesh',
      description: 'Scenic palm-fringed Godavari delta backwaters offering serene riverboat cruises, houseboats, and lush coconut plantation landscapes.',
      duration: '3.5 hours',
      estimatedCost: 250,
      latitude: 16.4350,
      longitude: 81.8210,
    },
    {
      name: 'Kolleru Lake Bird Sanctuary & Wetlands',
      category: 'Nature',
      location: 'Kolleru Lake, near Bhimavaram',
      address: 'Kolleru Bird Sanctuary, Andhra Pradesh',
      description: 'One of the largest freshwater wetland lakes in India, serving as a vital winter nesting habitat for thousands of migratory pelicans, painted storks, and herons.',
      duration: '3 hours',
      estimatedCost: 20,
      latitude: 16.6350,
      longitude: 81.3320,
    },
    {
      name: 'Alluri Sitarama Raju Memorial Park',
      category: 'Culture',
      location: 'Mogaltur Road, Bhimavaram',
      address: 'Bhimavaram Town, Andhra Pradesh',
      description: 'Historical memorial and park dedicated to the legendary freedom fighter Alluri Sitarama Raju, featuring bronze sculptures and landscaped public grounds.',
      duration: '1.5 hours',
      estimatedCost: 0,
      latitude: 16.5390,
      longitude: 81.5280,
    },
  ],
};

// Aliases for matching
const KEY_ALIASES = {
  vzm: 'vizianagaram',
  vizianagram: 'vizianagaram',
  vizianagaram: 'vizianagaram',
  vizag: 'visakhapatnam',
  visakhapatnam: 'visakhapatnam',
  waltair: 'visakhapatnam',
  bhimavaram: 'bhimavaram',
  bvrm: 'bhimavaram',
  patna: 'patna',
  pataliputra: 'patna',
  dimapur: 'dimapur',
  nagaland: 'dimapur',
  amritsar: 'amritsar',
  mumbai: 'mumbai',
  bombay: 'mumbai',
  jaipur: 'jaipur',
  delhi: 'delhi',
  'new delhi': 'delhi',
  goa: 'goa',
  kerala: 'kerala',
  munnar: 'kerala',
  kochi: 'kerala',
  cochin: 'kerala',
  alleppey: 'alappuzha',
  alappuzha: 'alappuzha',
  ladakh: 'ladakh',
  leh: 'ladakh',
  manali: 'manali',
  srinagar: 'srinagar',
  kashmir: 'srinagar',
  agra: 'agra',
};

function normalizeQuery(value) {
  return String(value || '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s]/g, '')
    .replace(/\s+/g, ' ');
}

function getCuratedAttractions(destinationName) {
  const norm = normalizeQuery(destinationName);
  if (!norm) return [];

  // 1. Exact alias match
  if (KEY_ALIASES[norm] && CURATED_ATTRACTIONS[KEY_ALIASES[norm]]) {
    return CURATED_ATTRACTIONS[KEY_ALIASES[norm]];
  }

  // 2. Strict word-boundary match (e.g. "patna city", "trip to patna", "jaipur rajasthan")
  for (const [key, target] of Object.entries(KEY_ALIASES)) {
    const keyWords = key.split(' ');
    // Check if whole key matches a word token in norm
    const regex = new RegExp(`\\b${key}\\b`, 'i');
    if (regex.test(norm)) {
      if (CURATED_ATTRACTIONS[target]) {
        return CURATED_ATTRACTIONS[target];
      }
    }
  }

  return [];
}

module.exports = {
  CURATED_ATTRACTIONS,
  getCuratedAttractions,
};
